"""country_table

Revision ID: b37ae9890096
Revises: 23d11d1fe4be
Create Date: 2024-08-23 12:55:53.167860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b37ae9890096'
down_revision = '23d11d1fe4be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('iso', sa.String(length=4), nullable=False),
    sa.Column('isd', sa.String(length=4), nullable=False),
    sa.Column('languageCode', sa.String(length=10), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('currencyCode', sa.String(length=10), nullable=False),
    sa.Column('currencySymbol', sa.String(length=10), nullable=False),
    sa.Column('minimumAge', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isd'),
    sa.UniqueConstraint('iso')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countries')
    # ### end Alembic commands ###
